name: Build and Package

on:
    workflow_dispatch: # 手动触发

jobs:
  build-and-package:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      # 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # 运行 libs-package.sh 脚本
      - name: Run libs-package.sh
        run: |
          chmod +x ./libs-package.sh
          ./libs-package.sh

      # 压缩 templates 文件夹为 ZIP
      - name: Zip templates folder
        run: |
          if [ -d "templates" ]; then
            zip -r templates.zip templates
          else
            echo "templates folder does not exist."
            exit 1
          fi
      
      # 根据 git hash 日期生成新的 release tag
      - name: Generate new release tag
        id: generate_tag
        run: |
          git_hash=$(git rev-parse --short HEAD)
          date_time=$(date +%Y%m%d%H%M%S)
          release_tag="resources-${git_hash}-${date_time}"
          echo "RELEASE_TAG=${release_tag}" >> $GITHUB_ENV
          echo "Generated release tag: $release_tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 检查 ZIP 文件是否存在
      - name: Check for ZIP files
        run: |
          if ls *.zip 1> /dev/null 2>&1; then
            echo "ZIP files found."
          else
            echo "No ZIP files found."
            exit 1
          fi

      # 创建新的 release
      - name: Create new release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_TAG }}"
          prerelease: false
          files: |
              *.zip